option to exclude version scripts
BigstickCarpet/version-bump-prompt pull request #40
Opened 2020-08-01 03:02 UTC by setshaft

implements a feature to skip specified version scripts from running by default with a new argument called --skip-version-scripts which defaults to []. 

Options can be preversion, postversion and version.

closes: https://github.com/JS-DevTools/version-bump-prompt/issues/39

2020-08-01 09:24 UTC, JamesMessinger requested changes
@setshaft - Thanks for the PR!  You did a great job on this, but I'd like to go with a boolean `--ignore-scripts` flag like NPM has, rather than a `--skip-version-scripts` array.   The array will cause conflicts/confusion with the `files` variadic argument. We _could_ take steps to mitigate that problem, but I don't think it's worthwhile, given that the primary use-case will be to skip _all_ NPM scripts, so a simple boolean flag works.

2020-08-01 09:24 UTC, JamesMessinger commented on src/cli/index.ts
> +    case ProgressEvent.ScriptSkipped:
No need to print a message for skipped scripts.  If they set the `--no-scripts` option, then we just won't print anything about the scripts, same as if they don't have scripts in their `package.json` file

2020-08-01 09:24 UTC, JamesMessinger commented on test/specs/files.spec.js
> +  it("should skip specified version scripts if present", () => {
This file is for tests related to the `[files...]` arg.  A better place to put this test would be in the `npm.spec.js` file, which is specifically for tests related to the npm version hooks

2020-08-04 04:06 UTC, setshaft commented
@JamesMessinger Sure, I will make changes when I have some free time and update you on this :)

2020-08-09 12:52 UTC, setshaft commented
@JamesMessinger  I have made the requested changes please take a look now 😊.

2020-08-22 03:49 UTC, sidtagirisa commented
Hi, @JamesMessinger please check the PR again. Thanks.

2020-08-29 14:25 UTC, JamesMessinger approved these changes

2020-08-29 14:25 UTC, merged

2020-08-29 14:27 UTC, JamesMessinger commented
Thanks for the great PR, @setshaft !  🏆💯   Sorry it took me so long to get it merged.  I've been working nights and weekends for the past couple of weeks 😓, so didn't have any time to spend on personal projects

2020-08-29 14:28 UTC, setshaft commented
@JamesMessinger No Problem 😊